Add partial moves example for `move_ref_pattern` stabilization
rust-lang/rust-by-example pull request #1377
Opened 2020-08-29 10:06 UTC by Amjad50

Documenting the *Partial move* pattern, which occurs when binding by ref and moving at the same time.

This is for stabilizing `move_ref_pattern` feature. (see rust-lang/rust#76049)

This is waiting for the stabilizing PR to be merged

2020-08-29 10:06 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @marioidival (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2020-09-28 18:45 UTC, marioidival approved these changes

2020-09-28 18:46 UTC, marioidival requested changes

2020-09-28 18:46 UTC, marioidival commented on src/scope/move/partial_move.md
> +    let Person { name, ref age } = person;
```failures:
---- /tmp/mdbook-f6BYlI/scope/move/partial_move.md - Partial_moves (line 10) stdout ----
error[E0658]: binding by-move and by-ref in the same pattern is unstable
  --> /tmp/mdbook-f6BYlI/scope/move/partial_move.md:24:18
   |
15 |     let Person { name, ref age } = person;
   |                  ^^^^  ------- by-ref pattern here
   |                  |
   |                  by-move pattern here
   |
   = note: see issue #68354 <https://github.com/rust-lang/rust/issues/68354> for more information
   = help: add `#![feature(move_ref_pattern)]` to the crate attributes to enable```

2020-09-29 05:21 UTC, Amjad50 commented on src/scope/move/partial_move.md
> +    let Person { name, ref age } = person;
waiting for stabilization (rust-lang/rust#76119)

2020-10-19 15:53 UTC, marioidival commented
@Amjad50 thank you!

2020-10-19 15:54 UTC, merged