Replace the "among us" reference with "here"
rust-lang/rust-by-example pull request #1417
Opened 2021-02-26 02:32 UTC by aaabot

I can't fucking take it. I see an image of a random object posted and then I see it, I fucking see it. "Oh that looks kinda like the among us guy" it started as. That's funny, that's a cool reference. But I kept going, I'd see a fridge that looked like among us, I'd see an animated bag of chips that looked like among us, I'd see a hat that looked like among us. And every time I'd burst into an insane, breath deprived laugh staring at the image as the words AMOGUS ran through my head. It's torment, psychological torture, I am being conditioned to laugh maniacly any time I see an oval on a red object. I can't fucking live like this... I can't I can't I can't I can't I can't! And don't get me fucking started on the words! I'll never hear the word suspicious again without thinking of among us. Someone does something bad and I can't say anything other than "sus." I could watch a man murder everyone I love and all I would be able to say is "red sus" and laugh like a fucking insane person. And the word "among" is ruined. The phrase "among us" is ruined. I can't live anymore. Among us has destroyed my fucking life. I want to eject myself from this plane of existence. MAKE IT STOP!

![Sus](https://i.kym-cdn.com/entries/icons/original/000/031/671/cover1.jpg)

2021-02-26 02:32 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @marioidival (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. Due to the way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-02-26 02:55 UTC, andraantariksa approved these changes

2021-02-27 14:43 UTC, Hazmi35 approved these changes

2021-02-27 16:41 UTC, silverben10 approved these changes

2021-02-28 03:05 UTC, parampaa2 approved these changes

2021-02-28 06:25 UTC, sam6321 approved these changes

2021-02-28 08:28 UTC, mochidaz approved these changes

2021-02-28 15:58 UTC, pedrohdjs approved these changes

2021-02-28 20:56 UTC, initpwn approved these changes

2021-03-01 00:28 UTC, DamageESP approved these changes

2021-03-03 14:08 UTC, prazeblaze approved these changes

2021-03-03 15:41 UTC, rakovskij-stanislav approved these changes

2021-03-03 15:58 UTC, paumue approved these changes

2021-03-03 16:04 UTC, mautamu approved these changes

2021-03-03 16:04 UTC, tacheometry approved these changes

2021-03-03 16:05 UTC, ReduxGB approved these changes

2021-03-03 16:06 UTC, ArsenArsen approved these changes

2021-03-03 16:10 UTC, betseg approved these changes

2021-03-03 16:15 UTC, echnobas approved these changes

2021-03-03 16:16 UTC, der-teufel-programming approved these changes

2021-03-03 16:18 UTC, haze approved these changes

2021-03-03 16:19 UTC, a-github-account commented
amogus

2021-03-03 16:19 UTC, joivo approved these changes

2021-03-03 16:20 UTC, g-w1 approved these changes

2021-03-03 16:22 UTC, ArkaneMoose approved these changes

2021-03-03 16:28 UTC, aspenluxxxy approved these changes

2021-03-03 16:31 UTC, Xe approved these changes

2021-03-03 16:32 UTC, Shizcow commented on src/flow_control/for.md
> +            &"Ferris" => println!("There is a rustacean here!"),
While I agree with the premise of this issue, I think the changes need a little work. How about `There is a rustacean in this foundation!`? It gets in a rhyme while giving a nod to the recently formed Rust Foundation. An actual improvement over the `among us` phrase.

2021-03-03 16:37 UTC, aveao approved these changes

2021-03-03 16:39 UTC, error56 approved these changes

2021-03-03 16:40 UTC, lordjbs approved these changes

2021-03-03 16:42 UTC, NahuLD approved these changes

2021-03-03 16:42 UTC, ivall approved these changes

2021-03-03 16:45 UTC, emiyl approved these changes

2021-03-03 16:46 UTC, Daggy1234 approved these changes

2021-03-03 16:46 UTC, averwhy approved these changes

2021-03-03 16:48 UTC, 0xpr03 requested changes
The code is 3 years old. Stop making it a problem and go outside.

2021-03-03 16:48 UTC, bramhaag approved these changes

2021-03-03 16:50 UTC, dzikoysk approved these changes

2021-03-03 16:51 UTC, Ewaldd approved these changes

2021-03-03 16:52 UTC, InvoxiPlayGames approved these changes

2021-03-03 16:53 UTC, silvanob approved these changes

2021-03-03 16:55 UTC, wiktorkuchta approved these changes

2021-03-03 16:55 UTC, TheEssem approved these changes

2021-03-03 17:00 UTC, the-emerald approved these changes

2021-03-03 17:21 UTC, closed without merging