store Person.age on the heap
rust-lang/rust-by-example pull request #1486
Opened 2022-01-03 18:39 UTC by FlorentCLMichel

I think that `ref` is not required in this example if Person.age is stored on the stack, as the definition of `age` copies the data instead of moving it. I have thus changed the code to store it on the heap, to illustrate the usefulness of `ref` in this context, and added a short explanation. 

An alternative possibility could be to use `name` instead of `age` for the illustration; not sure which is clearer. Please feel free to edit or request edits to this PR if you see a clearer way!

2022-01-03 18:39 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @marioidival (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-01-05 11:40 UTC, marioidival requested changes
just a typo

2022-01-05 11:40 UTC, marioidival commented on src/scope/move/partial_move.md
> +variable `age`. If `Person.age` were stored on the stack, `ref`would
```suggestion
variable `age`. If `Person.age` were stored on the stack, `ref` would 
```

2022-01-05 11:46 UTC, FlorentCLMichel commented on src/scope/move/partial_move.md
> +variable `age`. If `Person.age` were stored on the stack, `ref`would
Well spotted! Thanks!

2022-01-05 11:47 UTC, merged

2022-01-05 11:47 UTC, marioidival commented
@FlorentCLMichel thank you