Fix reference on Debug page: Display -> Debug
rust-lang/rust-by-example pull request #1494
Opened 2022-01-11 23:24 UTC by michallepicki

2022-01-11 23:24 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @marioidival (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2022-01-18 10:20 UTC, marioidival requested changes

2022-01-18 10:54 UTC, michallepicki commented on src/hello/print/print_debug.md
> +One can manually implement `fmt::Debug` to control the display.
Alright I can try, what do you think is wrong with this sentence?

2022-02-18 13:45 UTC, marioidival commented on src/hello/print/print_debug.md
> +One can manually implement `fmt::Debug` to control the display.
Sorry the delay, but I think you can explain more about how Debug are acting there. @michallepicki

2022-02-23 16:53 UTC, michallepicki commented
> you can explain more about how Debug are acting there

I don't fully understand what you want me to add, this whole page is about how Debug works, and this is a last sentence on the matter. I was reading this and at this point I understood pretty clearly how Debug works, and I was confused about a reference to `Display`, so I thought this is just a typo that needs to be corrected. If you think there's more information that needs to be added here maybe you'll be the more knowledgeable person to do that, I'll close this

2022-02-23 16:53 UTC, closed without merging