Remove awkward match in if_let
rust-lang/rust-by-example pull request #1725
Opened 2023-07-05 11:41 UTC by gepbird

I tried removing the braces from that code example and it compiled, so I assume this feature was introduced to rust after RBE was written thus the whole example became obsolete.
```rust
let optional = Some(7);
match optional {
  Some(i) => println!("This is a really long string and `{:?}`", i),
  _ => {}
};
```

2023-07-05 11:57 UTC, gepbird commented
The exhaustive `_` shouldn't be removed so I'm reverting the previous change and only removing the the block after `Some(i)`.

2023-07-07 22:46 UTC, marioidival commented
So, essentially you just remove the comments that could be useful for someone. I'll close this PR because do anything, ok @gepbird ?

2023-07-07 23:20 UTC, gepbird commented
Sorry, I didn't include the comment in the PR description, please check the changes.
I removed the brackets around `println!`. One comment said those brackets are necessary when they are not.

2023-08-22 18:51 UTC, marioidival requested changes
this snippet looks awkward because he's has a comment. I think should be fine!

2024-06-30 11:58 UTC, merged